; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Configuration File for Xiao ESP32-S3
; ------------------------------------------------
[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    https://github.com/Seeed-Studio/Grove_High_Precision_RTC_PCF85063TP.git
    https://github.com/Seeed-Studio/Seeed_SHT35.git
    olikraus/U8g2 @ ^2.35.9
    arduino-libraries/NTPClient @ ^3.2.1